apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: microbot
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: microbot 
    spec:
      containers:
      - name: microbot 
        image: dontrebootme/microbot 
        ports:
        - containerPort: 80
