apiVersion: v1
kind: Service
metadata:
  name: microbot 
  labels:
    name: microbot 
spec:
  type: NodePort
  ports:
    - port: 80
      nodePort: 30080
      name: http
  selector:
    app: microbot 
